// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyhrxmawczrztkzwtwol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5aHJ4bWF3Y3pyenRrend0d29sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NjU5NTMsImV4cCI6MjA2MTE0MTk1M30.Qog93Uit7snzcq5Q6lYAKrcJEC1Qsqzr-PmlXaOBrjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);